// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

using System;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.JavaScript;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Varve.Store.Browser;

/// <summary>
/// The calls into <see cref="StorageModule"/>, generated by the
/// <c>[JSImport]</c> source generator: no reflection, nothing for the trimmer
/// to guess at (ADR 0084).
/// </summary>
/// <remarks>
/// The generator emits unsafe code, which is why this package, alone among
/// the shipped ones, compiles with <c>AllowUnsafeBlocks</c>; no line written
/// here is unsafe (ADR 0084). A <see cref="Span{T}"/> crosses as a memory view
/// that is valid only for the call, so an asynchronous call takes bytes the
/// module has staged first.
/// </remarks>
internal static partial class Interop
{
    /// <summary>
    /// Imports the module from a <c>data:</c> URL. Called by every open: the
    /// browser's module map makes a second import of the same URL the first
    /// one's module, so no state is kept here.
    /// </summary>
    public static Task EnsureImportedAsync(CancellationToken cancellationToken) =>
        JSHost.ImportAsync(
            StorageModule.Name,
            "data:text/javascript;base64," + Convert.ToBase64String(Encoding.UTF8.GetBytes(StorageModule.Source)),
            cancellationToken);

    [JSImport("opfsAvailable", StorageModule.Name)]
    public static partial bool OpfsAvailable();

    [JSImport("indexedDbAvailable", StorageModule.Name)]
    public static partial bool IndexedDbAvailable();

    [JSImport("opfsDirectory", StorageModule.Name)]
    public static partial Task<JSObject> OpfsDirectory(string path);

    [JSImport("opfsChild", StorageModule.Name)]
    public static partial Task<JSObject> OpfsChild(JSObject directory, string name);

    [JSImport("opfsFiles", StorageModule.Name)]
    public static partial Task<string> OpfsFiles(JSObject directory);

    [JSImport("opfsOpen", StorageModule.Name)]
    public static partial Task<JSObject?> OpfsOpen(JSObject directory, string path, bool create);

    [JSImport("opfsMove", StorageModule.Name)]
    public static partial Task<int> OpfsMove(JSObject directory, string from, string to);

    [JSImport("opfsRemove", StorageModule.Name)]
    public static partial Task<int> OpfsRemove(JSObject directory, string path);

    [JSImport("opfsReadText", StorageModule.Name)]
    public static partial Task<string?> OpfsReadText(JSObject directory, string path);

    [JSImport("syncRead", StorageModule.Name)]
    public static partial int SyncRead(JSObject handle, [JSMarshalAs<JSType.MemoryView>] Span<byte> destination, double at);

    [JSImport("syncWrite", StorageModule.Name)]
    public static partial int SyncWrite(JSObject handle, [JSMarshalAs<JSType.MemoryView>] Span<byte> source, double at);

    [JSImport("syncFlush", StorageModule.Name)]
    public static partial void SyncFlush(JSObject handle);

    [JSImport("syncSize", StorageModule.Name)]
    public static partial double SyncSize(JSObject handle);

    [JSImport("syncTruncate", StorageModule.Name)]
    public static partial void SyncTruncate(JSObject handle, double size);

    [JSImport("syncClose", StorageModule.Name)]
    public static partial void SyncClose(JSObject handle);

    [JSImport("idbOpen", StorageModule.Name)]
    public static partial Task<JSObject> IdbOpen(string name);

    [JSImport("idbClose", StorageModule.Name)]
    public static partial void IdbClose(JSObject database);

    [JSImport("idbSegments", StorageModule.Name)]
    public static partial Task<string> IdbSegments(JSObject database);

    [JSImport("idbReadRange", StorageModule.Name)]
    public static partial Task<JSObject> IdbReadRange(JSObject database, double segment, double offset, double length);

    [JSImport("idbAppend", StorageModule.Name)]
    public static partial Task IdbAppend(JSObject database, double segment, double offset, JSObject bytes, double length, bool sealedSegment);

    [JSImport("idbGetMeta", StorageModule.Name)]
    public static partial Task<JSObject?> IdbGetMeta(JSObject database, string key);

    [JSImport("idbPutMetaOnce", StorageModule.Name)]
    public static partial Task<bool> IdbPutMetaOnce(JSObject database, string key, JSObject bytes);

    [JSImport("idbGetBlob", StorageModule.Name)]
    public static partial Task<JSObject?> IdbGetBlob(JSObject database, string name);

    [JSImport("idbPutBlob", StorageModule.Name)]
    public static partial Task IdbPutBlob(JSObject database, string name, JSObject bytes);

    [JSImport("idbDeleteBlob", StorageModule.Name)]
    public static partial Task<bool> IdbDeleteBlob(JSObject database, string name);

    [JSImport("idbBlobNames", StorageModule.Name)]
    public static partial Task<string> IdbBlobNames(JSObject database);

    [JSImport("lockAcquire", StorageModule.Name)]
    public static partial Task<JSObject?> LockAcquire(string name);

    [JSImport("lockRelease", StorageModule.Name)]
    public static partial void LockRelease(JSObject held);

    [JSImport("stage", StorageModule.Name)]
    public static partial JSObject Stage([JSMarshalAs<JSType.MemoryView>] Span<byte> source);

    [JSImport("byteLength", StorageModule.Name)]
    public static partial int ByteLength(JSObject bytes);

    [JSImport("copyOut", StorageModule.Name)]
    public static partial void CopyOut(JSObject bytes, int offset, [JSMarshalAs<JSType.MemoryView>] Span<byte> destination);

    /// <summary>A JavaScript <c>Uint8Array</c>, copied into a managed array.</summary>
    public static byte[] ToArray(JSObject bytes)
    {
        byte[] result = new byte[ByteLength(bytes)];
        CopyOut(bytes, 0, result);
        return result;
    }

    /// <summary>Bytes the caller lends, staged for an asynchronous call.</summary>
    /// <remarks>The module only reads the view, and copies it.</remarks>
    public static JSObject Stage(ReadOnlyMemory<byte> bytes) => Stage(MemoryMarshal.AsMemory(bytes).Span);

    /// <summary>Writes bytes the caller lends through a synchronous access handle.</summary>
    /// <remarks>The module only reads the view.</remarks>
    public static int Write(JSObject handle, ReadOnlyMemory<byte> bytes, long at) =>
        SyncWrite(handle, MemoryMarshal.AsMemory(bytes).Span, at);
}
