<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <VarveLayer>none</VarveLayer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Varve.Sparql/Varve.Sparql.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="CsCheck" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../AllocationMeter.cs" Link="AllocationMeter.cs" />
  </ItemGroup>

</Project>
