// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Issue reference gate.
//
//   dotnet run eng/issue-refs.cs -- [--base <ref>] [--head <ref>]
//   dotnet run eng/issue-refs.cs -- --range <a>..<b>
//
// ADR 0033: every commit on main references a tracked issue, as "Refs #N" for
// a commit that contributes to one or "Closes #N" for one that completes it,
// in the commit body. This fails when a commit in the range carries neither.
//
// Why a gate rather than a convention. ADR 0032 made pull requests optional, so
// a rule enforced by a pull request template would bind one of the two routes
// to the trunk and leave the other — now a first-class route — untraced. The
// two decisions only work together.
//
// Merge commits are exempt, by parent count. A merge's message is generated by
// GitHub and describes the merge rather than the work, and the commits it
// brings are each checked on their own. A merge that does carry a reference is
// accepted and this repository's merges carry one.
//
// Commits authored by a known bot are exempt too, and this one is a concession
// rather than a principle. Dependabot writes its own commit message and cannot
// be configured to add a body, so there is no setting that would make its
// commits carry "Refs #N". The choice is between exempting them and refusing
// automated dependency updates altogether, and the pull request Dependabot
// opens is a tracking artefact of its own. The list is closed and explicit:
// widening it is how this gate would stop meaning anything.
//
// Exactly two forms are accepted, and a bare "#N" is not one of them: "#N"
// appears in ordinary prose often enough ("as #12 describes") that accepting it
// would pass commits that reference nothing deliberately. The keyword is
// matched case-insensitively — failing a build over "refs" would teach nobody
// anything — but Refs and Closes are the spellings to write.
//
// What this deliberately does not do: check that the issue exists. That needs a
// network call and a token, which would make a gate that must run offline in a
// devcontainer depend on GitHub being reachable. A reference to a closed or
// non-existent issue is review's job.
//
// The range, when not given, is worked out from the environment: a pull request
// gives GITHUB_BASE_REF, a push gives the before and after shas, and a local
// run falls back to origin/main..HEAD.
//
// Exit codes: 0 conformant, 1 findings, 2 could not run.
//
// See docs/adr/0033-commit-traceability.md.

using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;

string repositoryRoot = FindRepositoryRoot();

string? baseRef = null;
string? headRef = null;
string? explicitRange = null;

string[] arguments = args;
for (int i = 0; i < arguments.Length; i++)
{
    if (arguments[i] is "--base" && i + 1 < arguments.Length)
    {
        baseRef = arguments[++i];
    }
    else if (arguments[i] is "--head" && i + 1 < arguments.Length)
    {
        headRef = arguments[++i];
    }
    else if (arguments[i] is "--range" && i + 1 < arguments.Length)
    {
        explicitRange = arguments[++i];
    }
}

string range = explicitRange ?? ResolveRange(repositoryRoot, baseRef, headRef);

Console.WriteLine($"note range: {range}");

// --- read the commits ------------------------------------------------------

// One git call for the whole range. \u0001 opens a record, \u0003 separates the
// shas from the author name and \u0002 separates the header from the message,
// so a message containing anything at all cannot be confused for a delimiter.
(int exitCode, string stdout, string stderr) = Git(repositoryRoot, "log", "--format=%x01%H %P%x03%an%x02%B", range);

if (exitCode != 0)
{
    Console.Error.WriteLine($"issue-refs: could not read '{range}': {stderr.Trim()}");
    Console.Error.WriteLine("issue-refs: in a shallow clone the base may not be present. Fetch it, or pass --range.");
    return 2;
}

Regex reference = new(@"\b(?:Refs|Closes)\s+#\d+\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

// Closed and explicit. See the note above before adding to it.
HashSet<string> exemptAuthors = new(StringComparer.OrdinalIgnoreCase)
{
    "dependabot[bot]",
    "github-actions[bot]",
};

List<(string Sha, string Subject)> missing = [];
int checkedCommits = 0;
int merges = 0;
int automated = 0;

foreach (string record in stdout.Split('\u0001', StringSplitOptions.RemoveEmptyEntries))
{
    int split = record.IndexOf('\u0002');

    if (split < 0)
    {
        Console.Error.WriteLine("issue-refs: git log returned a record with no message separator.");
        return 2;
    }

    string header = record[..split];
    int authorSplit = header.IndexOf('\u0003');

    if (authorSplit < 0)
    {
        Console.Error.WriteLine("issue-refs: git log returned a record with no author separator.");
        return 2;
    }

    string[] shas = header[..authorSplit].Split(' ', StringSplitOptions.RemoveEmptyEntries);
    string sha = shas[0];
    int parents = shas.Length - 1;
    string author = header[(authorSplit + 1)..].Trim();
    string message = record[(split + 1)..];

    if (parents > 1)
    {
        merges++;
        continue;
    }

    if (exemptAuthors.Contains(author))
    {
        automated++;
        continue;
    }

    checkedCommits++;

    string[] lines = message.Split('\n');
    string subject = lines.Length > 0 ? lines[0].Trim() : string.Empty;

    // The subject is excluded on purpose: "Closes #12" as a whole subject line
    // says what the commit does to an issue but leaves the commit with no
    // message, and ADR 0033 puts the reference in the body.
    string body = lines.Length > 1 ? string.Join('\n', lines[1..]) : string.Empty;

    if (!reference.IsMatch(body))
    {
        missing.Add((sha[..Math.Min(8, sha.Length)], subject));
    }
}

// --- report ----------------------------------------------------------------

string summary = BuildSummary(checkedCommits, merges, automated, missing.Count);

Console.WriteLine(summary);

string? stepSummary = Environment.GetEnvironmentVariable("GITHUB_STEP_SUMMARY");
if (!string.IsNullOrEmpty(stepSummary))
{
    File.AppendAllText(stepSummary, summary + Environment.NewLine);
}

if (checkedCommits == 0 && merges == 0 && automated == 0)
{
    Console.WriteLine("ok  no commits in range");
    return 0;
}

if (missing.Count == 0)
{
    Console.WriteLine($"ok  {checkedCommits} commit(s) reference an issue");
    return 0;
}

Console.Error.WriteLine();
Console.Error.WriteLine($"FAIL: {missing.Count} of {checkedCommits} commit(s) reference no issue.");
Console.Error.WriteLine();
Console.Error.WriteLine("ADR 0033: every commit on main is tied to a tracked issue. Put one of");
Console.Error.WriteLine("these in the commit body — not the subject:");
Console.Error.WriteLine();
Console.Error.WriteLine("  Refs #N      the commit contributes to issue N");
Console.Error.WriteLine("  Closes #N    the commit completes issue N");
Console.Error.WriteLine();
Console.Error.WriteLine("git commit --amend, or git rebase -i to reach an older one.");
Console.Error.WriteLine();

foreach ((string sha, string subject) in missing)
{
    Console.Error.WriteLine($"  {sha}  {subject}");
}

Console.Error.WriteLine();
Console.Error.WriteLine("See docs/adr/0033-commit-traceability.md.");

return 1;

// --- helpers ---------------------------------------------------------------

static string BuildSummary(int checkedCommits, int merges, int automated, int missing)
{
    StringBuilder builder = new();

    builder.AppendLine("## Issue references");
    builder.AppendLine();
    builder.AppendLine("| Commits checked | Merges skipped | Automated skipped | Without a reference |");
    builder.AppendLine("|---:|---:|---:|---:|");
    builder.AppendLine($"| {checkedCommits} | {merges} | {automated} | {missing} |");

    return builder.ToString().TrimEnd();
}

static string ResolveRange(string root, string? baseRef, string? headRef)
{
    string head = headRef ?? Environment.GetEnvironmentVariable("GITHUB_SHA") ?? "HEAD";

    if (baseRef is not null)
    {
        return $"{baseRef}..{head}";
    }

    // A pull request. GITHUB_BASE_REF is a branch name, and the checkout has it
    // as a remote-tracking ref rather than a local branch.
    string? prBase = Environment.GetEnvironmentVariable("GITHUB_BASE_REF");

    if (!string.IsNullOrEmpty(prBase))
    {
        return $"origin/{prBase}..{head}";
    }

    // A push. GITHUB_EVENT_BEFORE is all zeroes for a branch's first push,
    // where there is no before to compare against.
    string? before = Environment.GetEnvironmentVariable("GITHUB_EVENT_BEFORE");

    if (!string.IsNullOrEmpty(before) && before.Trim('0').Length > 0 && Exists(root, before))
    {
        return $"{before}..{head}";
    }

    // Local, or a first push. origin/main is the trunk (ADR 0032), and anything
    // not on it is what this run is responsible for.
    return Exists(root, "origin/main") ? $"origin/main..{head}" : $"main..{head}";
}

static bool Exists(string root, string reference) =>
    Git(root, "rev-parse", "--verify", "--quiet", reference + "^{commit}").ExitCode == 0;

static (int ExitCode, string StandardOutput, string StandardError) Git(string root, params string[] arguments)
{
    ProcessStartInfo startInfo = new()
    {
        FileName = "git",
        WorkingDirectory = root,
        RedirectStandardOutput = true,
        RedirectStandardError = true,
        UseShellExecute = false,
    };

    foreach (string argument in arguments)
    {
        startInfo.ArgumentList.Add(argument);
    }

    using Process process = Process.Start(startInfo)
        ?? throw new InvalidOperationException("Could not start git.");

    string standardOutput = process.StandardOutput.ReadToEnd();
    string standardError = process.StandardError.ReadToEnd();
    process.WaitForExit();

    return (process.ExitCode, standardOutput, standardError);
}

static string FindRepositoryRoot()
{
    DirectoryInfo? directory = new(Directory.GetCurrentDirectory());

    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "Varve.slnx")))
        {
            return directory.FullName;
        }

        directory = directory.Parent;
    }

    throw new InvalidOperationException("Could not find the repository root (no Varve.slnx above the current directory).");
}
