// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Licence header gate.
//
//   dotnet run eng/licence-headers.cs -- [--root <path>]
//
// ADR 0031 relicensed this repository to MPL-2.0, which is a file-level
// copyleft licence. "File-level" is not a figure of speech: MPL-2.0 attaches
// its reciprocity to each file carrying the Exhibit A notice, and §1.4 defines
// Covered Software as the Source Code Form "to which the initial Contributor
// has attached the notice in Exhibit A". A source file without the notice is
// not obviously covered, and a licence whose scope depends on a header that
// nobody checks is a licence that erodes one new file at a time.
//
// So this fails the build when a .cs file does not begin with the notice,
// exactly as Exhibit A words it:
//
//   // This Source Code Form is subject to the terms of the Mozilla Public
//   // License, v. 2.0. If a copy of the MPL was not distributed with this
//   // file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// The match is on the first three lines rather than anywhere in the file,
// because Exhibit A says the notice is attached to the file and a reader
// looking for a licence looks at the top. A byte order mark before it is
// allowed; nothing else is.
//
// Generated code is excepted by pattern — *.g.cs, *.generated.cs,
// *.Designer.cs, and any file whose opening lines carry the marker the Roslyn
// and designer toolchains write. A header on a file a tool rewrites is a header
// that survives until the next build. Nothing generated is checked into this
// repository today; the exception exists so that the first source generator
// does not have to argue with this gate.
//
// The marker is spelled out once, in IsGenerated below, and deliberately not
// here: the compiler decides a file is generated by looking for it in the
// file's *leading* comment, so writing it in this banner makes the compiler
// treat this gate as generated code and reject its own nullable annotations
// with CS8669. That is not a hypothetical — it is what the first run did.
//
// --root aims the gate at a directory, which is how its failure path is proven:
// tests/fixtures/licence-header/ holds one file with the notice and one
// without, and that directory is excluded from the repository-wide run for the
// same reason tests/fixtures/banned-api/ is outside the solution.
//
// Exit codes: 0 conformant, 1 findings, 2 could not run.
//
// See docs/adr/0031-licence-mpl-2-0.md.

using System.Text;

string repositoryRoot = FindRepositoryRoot();
string scanRoot = repositoryRoot;

string[] arguments = args;
for (int i = 0; i < arguments.Length; i++)
{
    if (arguments[i] is "--root" && i + 1 < arguments.Length)
    {
        scanRoot = Path.GetFullPath(arguments[++i]);
    }
}

if (!Directory.Exists(scanRoot))
{
    Console.Error.WriteLine($"licence-headers: no directory at '{scanRoot}'.");
    return 2;
}

// The notice, verbatim from Exhibit A of the licence text in LICENSE. The
// wrapping is Exhibit A's own; do not reflow it.
string[] notice =
[
    "// This Source Code Form is subject to the terms of the Mozilla Public",
    "// License, v. 2.0. If a copy of the MPL was not distributed with this",
    "// file, You can obtain one at https://mozilla.org/MPL/2.0/.",
];

// Directory names that are never source we own, at any depth.
HashSet<string> skippedDirectories = new(StringComparer.Ordinal)
{
    ".git",
    "bin",
    "obj",
    "artifacts",
    "node_modules",
    "BenchmarkDotNet.Artifacts",
};

// Paths excluded as a whole, relative to the repository root and in the
// repository's own separator. The W3C suite is a submodule carrying someone
// else's licence; the fixture is this gate's failure path.
//
// These apply to the repository-wide run only. An explicit --root is someone
// aiming the gate at a directory on purpose, and it would be useless if the
// gate answered "nothing to check" for the one directory whose whole reason to
// exist is to be checked.
string[] excludedPaths = scanRoot == repositoryRoot
    ?
    [
        Path.Combine("tests", "w3c"),
        Path.Combine("tests", "fixtures", "licence-header"),
    ]
    : [];

string[] generatedSuffixes = [".g.cs", ".g.i.cs", ".generated.cs", ".Designer.cs"];

List<string> missing = [];
List<string> skippedAsGenerated = [];
int checkedFiles = 0;

foreach (string file in Directory.EnumerateFiles(scanRoot, "*.cs", SearchOption.AllDirectories).OrderBy(static path => path, StringComparer.Ordinal))
{
    if (IsUnderSkippedDirectory(file, scanRoot, skippedDirectories))
    {
        continue;
    }

    string fromRepositoryRoot = Relative(repositoryRoot, file);

    if (excludedPaths.Any(excluded => fromRepositoryRoot.StartsWith(excluded + Path.DirectorySeparatorChar, StringComparison.Ordinal)))
    {
        continue;
    }

    string[] lines;
    try
    {
        lines = File.ReadAllLines(file, Encoding.UTF8);
    }
    catch (IOException exception)
    {
        Console.Error.WriteLine($"licence-headers: could not read '{Relative(repositoryRoot, file)}': {exception.Message}");
        return 2;
    }

    if (IsGenerated(file, lines, generatedSuffixes))
    {
        skippedAsGenerated.Add(Relative(repositoryRoot, file));
        continue;
    }

    checkedFiles++;

    if (!StartsWithNotice(lines, notice))
    {
        missing.Add(Relative(repositoryRoot, file));
    }
}

// --- report ----------------------------------------------------------------

if (checkedFiles == 0)
{
    Console.Error.WriteLine($"licence-headers: no .cs files under '{scanRoot}'. That is almost certainly a wrong --root rather than a clean tree.");
    return 2;
}

foreach (string file in skippedAsGenerated)
{
    Console.WriteLine($"note generated, not checked: {file}");
}

if (missing.Count == 0)
{
    Console.WriteLine($"ok  {checkedFiles} .cs files carry the MPL-2.0 notice");
    return 0;
}

Console.Error.WriteLine();
Console.Error.WriteLine($"FAIL: {missing.Count} of {checkedFiles} .cs files do not begin with the MPL-2.0 notice.");
Console.Error.WriteLine();
Console.Error.WriteLine("MPL-2.0 covers a file because the file says so (§1.4, Exhibit A). Add these");
Console.Error.WriteLine("three lines as the first three lines of each file below:");
Console.Error.WriteLine();

foreach (string line in notice)
{
    Console.Error.WriteLine($"  {line}");
}

Console.Error.WriteLine();

foreach (string file in missing)
{
    Console.Error.WriteLine($"  {file}");
}

Console.Error.WriteLine();
Console.Error.WriteLine("See docs/adr/0031-licence-mpl-2-0.md.");

return 1;

// --- helpers ---------------------------------------------------------------

static bool StartsWithNotice(string[] lines, string[] notice)
{
    if (lines.Length < notice.Length)
    {
        return false;
    }

    for (int i = 0; i < notice.Length; i++)
    {
        // A byte order mark is stripped by the reader on line 0 in most cases,
        // but not all encodings round-trip it that way. Trimming it here costs
        // nothing and removes a failure nobody could diagnose from the message.
        string line = lines[i].TrimStart('﻿');

        if (!string.Equals(line, notice[i], StringComparison.Ordinal))
        {
            return false;
        }
    }

    return true;
}

static bool IsGenerated(string path, string[] lines, string[] generatedSuffixes)
{
    string name = Path.GetFileName(path);

    if (generatedSuffixes.Any(suffix => name.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)))
    {
        return true;
    }

    // The marker the Roslyn and designer toolchains write. Only the opening
    // lines count: the words could appear in a comment much further down, and a
    // file is not generated because it mentions generation.
    int scanned = Math.Min(lines.Length, 3);

    for (int i = 0; i < scanned; i++)
    {
        if (lines[i].Contains("<auto-generated", StringComparison.Ordinal))
        {
            return true;
        }
    }

    return false;
}

static bool IsUnderSkippedDirectory(string file, string scanRoot, HashSet<string> skipped)
{
    string? directory = Path.GetDirectoryName(file);

    while (directory is not null && directory.Length >= scanRoot.Length)
    {
        if (skipped.Contains(Path.GetFileName(directory)))
        {
            return true;
        }

        directory = Path.GetDirectoryName(directory);
    }

    return false;
}

static string Relative(string root, string path) =>
    path.StartsWith(root, StringComparison.Ordinal) ? path[(root.Length + 1)..] : path;

static string FindRepositoryRoot()
{
    DirectoryInfo? directory = new(Directory.GetCurrentDirectory());

    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "Varve.slnx")))
        {
            return directory.FullName;
        }

        directory = directory.Parent;
    }

    throw new InvalidOperationException("Could not find the repository root (no Varve.slnx above the current directory).");
}
